
spring:
  application:
    name: spring-cloud-k8s-config-controller
  cloud:
    bus:
      enabled: true

k8s:
  informer:
    watcher-interval: 30
    configmap-label-enabled: config.spring.io/enabled
    configmap-label-label: condfig.spring.io/label
    configmap-label-profile: config.spring.io/profile
    bus: false

dekorate:
  kubernetes:
    name: sck8s_config_controller
    ports:
      - name: web
        container-port: 8080

#logging:
#  level:
#    root: INFO
#    io.agilehandy.k8s.configmap: INFO


management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
  
---
spring:
  profiles: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true

k8s:
  informer:
    bus: true


